tests/upgrade: Temporarily exclude "cas" app
Initially enabling the app fails with the following SQL error:

  ERROR:  index "primary" does not exist
  STATEMENT:  DROP INDEX "primary"

This apparently was introduced by actually wanting to fix things for
PostgreSQL as others have reported the issue upstream afterwards[1].

[1]: https://github.com/mziech/nextcloud-cas/issues/5#issuecomment-1021221776

Signed-off-by: aszlig <aszlig@nix.build>